// AUTO-GENERATED by scripts/generate-data.js — do not hand-edit.
// Regenerate with: node scripts/generate-data.js
//
// 100 deterministic mock applicants for the Pega training exercise.
// The first 10 entries (APP1001-APP1010) are
// deliberate name collisions in 5 pairs, so a name-only search on
// Applicant Search reliably returns multiple matches for the disambiguation exercise:
//   - Jonas Berger
//   - Anna Huber
//   - Maria Novak
//   - Tom Fischer
//   - Lena Wolf
// All other entries are randomized (fixed seed, so this file is reproducible).

const applicants = {
  "APP1001": {
    "applicantId": "APP1001",
    "ssn": "111-22-1001",
    "firstName": "Jonas",
    "lastName": "Berger",
    "dateOfBirth": "1992-02-03",
    "address": {
      "street": "42 Schoenbrunner Str",
      "city": "Vienna",
      "postalCode": "1150",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 137000,
    "creditScore": 605,
    "riskBand": "Poor"
  },
  "APP1002": {
    "applicantId": "APP1002",
    "ssn": "111-22-1002",
    "firstName": "Jonas",
    "lastName": "Berger",
    "dateOfBirth": "2001-09-09",
    "address": {
      "street": "67 Mariahilfer Str",
      "city": "Vienna",
      "postalCode": "1070",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 94000,
    "creditScore": 679,
    "riskBand": "Fair"
  },
  "APP1003": {
    "applicantId": "APP1003",
    "ssn": "111-22-1003",
    "firstName": "Anna",
    "lastName": "Huber",
    "dateOfBirth": "1999-12-19",
    "address": {
      "street": "68 Alserbachstrasse",
      "city": "Vienna",
      "postalCode": "1200",
      "country": "AT"
    },
    "employmentStatus": "Self-Employed",
    "annualIncome": 84000,
    "creditScore": 523,
    "riskBand": "Very Poor"
  },
  "APP1004": {
    "applicantId": "APP1004",
    "ssn": "111-22-1004",
    "firstName": "Anna",
    "lastName": "Huber",
    "dateOfBirth": "1967-07-24",
    "address": {
      "street": "75 Gumpendorfer Str",
      "city": "Vienna",
      "postalCode": "1100",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 41000,
    "creditScore": 525,
    "riskBand": "Very Poor"
  },
  "APP1005": {
    "applicantId": "APP1005",
    "ssn": "111-22-1005",
    "firstName": "Maria",
    "lastName": "Novak",
    "dateOfBirth": "1972-12-07",
    "address": {
      "street": "12 Favoritenstrasse",
      "city": "Vienna",
      "postalCode": "1030",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 35000,
    "creditScore": 512,
    "riskBand": "Very Poor"
  },
  "APP1006": {
    "applicantId": "APP1006",
    "ssn": "111-22-1006",
    "firstName": "Maria",
    "lastName": "Novak",
    "dateOfBirth": "1982-07-17",
    "address": {
      "street": "71 Westbahnstrasse",
      "city": "Vienna",
      "postalCode": "1030",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 75000,
    "creditScore": 604,
    "riskBand": "Poor"
  },
  "APP1007": {
    "applicantId": "APP1007",
    "ssn": "111-22-1007",
    "firstName": "Tom",
    "lastName": "Fischer",
    "dateOfBirth": "1987-10-28",
    "address": {
      "street": "86 Ringstrasse",
      "city": "Vienna",
      "postalCode": "1150",
      "country": "AT"
    },
    "employmentStatus": "Self-Employed",
    "annualIncome": 60000,
    "creditScore": 520,
    "riskBand": "Very Poor"
  },
  "APP1008": {
    "applicantId": "APP1008",
    "ssn": "111-22-1008",
    "firstName": "Tom",
    "lastName": "Fischer",
    "dateOfBirth": "1982-01-24",
    "address": {
      "street": "25 Schoenbrunner Str",
      "city": "Vienna",
      "postalCode": "1100",
      "country": "AT"
    },
    "employmentStatus": "Unemployed",
    "annualIncome": 0,
    "creditScore": 490,
    "riskBand": "Very Poor"
  },
  "APP1009": {
    "applicantId": "APP1009",
    "ssn": "111-22-1009",
    "firstName": "Lena",
    "lastName": "Wolf",
    "dateOfBirth": "1977-07-23",
    "address": {
      "street": "76 Neubaugasse",
      "city": "Vienna",
      "postalCode": "1150",
      "country": "AT"
    },
    "employmentStatus": "Self-Employed",
    "annualIncome": 77000,
    "creditScore": 607,
    "riskBand": "Poor"
  },
  "APP1010": {
    "applicantId": "APP1010",
    "ssn": "111-22-1010",
    "firstName": "Lena",
    "lastName": "Wolf",
    "dateOfBirth": "1990-07-21",
    "address": {
      "street": "89 Praterstrasse",
      "city": "Vienna",
      "postalCode": "1200",
      "country": "AT"
    },
    "employmentStatus": "Unemployed",
    "annualIncome": 0,
    "creditScore": 408,
    "riskBand": "Very Poor"
  },
  "APP1011": {
    "applicantId": "APP1011",
    "ssn": "111-22-1011",
    "firstName": "Eva",
    "lastName": "Winkler",
    "dateOfBirth": "1966-03-19",
    "address": {
      "street": "18 Westbahnstrasse",
      "city": "Vienna",
      "postalCode": "1010",
      "country": "AT"
    },
    "employmentStatus": "Self-Employed",
    "annualIncome": 47000,
    "creditScore": 545,
    "riskBand": "Very Poor"
  },
  "APP1012": {
    "applicantId": "APP1012",
    "ssn": "111-22-1012",
    "firstName": "Anna",
    "lastName": "Schmid",
    "dateOfBirth": "1971-12-10",
    "address": {
      "street": "47 Mariahilfer Str",
      "city": "Vienna",
      "postalCode": "1090",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 139000,
    "creditScore": 696,
    "riskBand": "Fair"
  },
  "APP1013": {
    "applicantId": "APP1013",
    "ssn": "111-22-1013",
    "firstName": "Clara",
    "lastName": "Wolf",
    "dateOfBirth": "1996-06-08",
    "address": {
      "street": "76 Hauptstrasse",
      "city": "Vienna",
      "postalCode": "1060",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 129000,
    "creditScore": 589,
    "riskBand": "Poor"
  },
  "APP1014": {
    "applicantId": "APP1014",
    "ssn": "111-22-1014",
    "firstName": "Lena",
    "lastName": "Bauer",
    "dateOfBirth": "1985-04-06",
    "address": {
      "street": "50 Gumpendorfer Str",
      "city": "Vienna",
      "postalCode": "1010",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 81000,
    "creditScore": 592,
    "riskBand": "Poor"
  },
  "APP1015": {
    "applicantId": "APP1015",
    "ssn": "111-22-1015",
    "firstName": "Jonas",
    "lastName": "Gruber",
    "dateOfBirth": "1992-03-15",
    "address": {
      "street": "26 Mariahilfer Str",
      "city": "Vienna",
      "postalCode": "1010",
      "country": "AT"
    },
    "employmentStatus": "Unemployed",
    "annualIncome": 0,
    "creditScore": 446,
    "riskBand": "Very Poor"
  },
  "APP1016": {
    "applicantId": "APP1016",
    "ssn": "111-22-1016",
    "firstName": "Jonas",
    "lastName": "Bauer",
    "dateOfBirth": "1985-04-17",
    "address": {
      "street": "6 Landstrasser Hauptstr",
      "city": "Vienna",
      "postalCode": "1010",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 88000,
    "creditScore": 652,
    "riskBand": "Fair"
  },
  "APP1017": {
    "applicantId": "APP1017",
    "ssn": "111-22-1017",
    "firstName": "Julia",
    "lastName": "Huber",
    "dateOfBirth": "2001-07-11",
    "address": {
      "street": "26 Neubaugasse",
      "city": "Vienna",
      "postalCode": "1120",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 73000,
    "creditScore": 627,
    "riskBand": "Poor"
  },
  "APP1018": {
    "applicantId": "APP1018",
    "ssn": "111-22-1018",
    "firstName": "Hannah",
    "lastName": "Gruber",
    "dateOfBirth": "1970-04-26",
    "address": {
      "street": "56 Gumpendorfer Str",
      "city": "Vienna",
      "postalCode": "1030",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 45000,
    "creditScore": 602,
    "riskBand": "Poor"
  },
  "APP1019": {
    "applicantId": "APP1019",
    "ssn": "111-22-1019",
    "firstName": "Julia",
    "lastName": "Winkler",
    "dateOfBirth": "1966-07-22",
    "address": {
      "street": "45 Taborstrasse",
      "city": "Vienna",
      "postalCode": "1120",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 98000,
    "creditScore": 538,
    "riskBand": "Very Poor"
  },
  "APP1020": {
    "applicantId": "APP1020",
    "ssn": "111-22-1020",
    "firstName": "Sarah",
    "lastName": "Lang",
    "dateOfBirth": "1994-11-01",
    "address": {
      "street": "35 Ringstrasse",
      "city": "Vienna",
      "postalCode": "1090",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 135000,
    "creditScore": 602,
    "riskBand": "Poor"
  },
  "APP1021": {
    "applicantId": "APP1021",
    "ssn": "111-22-1021",
    "firstName": "Lena",
    "lastName": "Brunner",
    "dateOfBirth": "1981-12-06",
    "address": {
      "street": "70 Gumpendorfer Str",
      "city": "Vienna",
      "postalCode": "1030",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 64000,
    "creditScore": 621,
    "riskBand": "Poor"
  },
  "APP1022": {
    "applicantId": "APP1022",
    "ssn": "111-22-1022",
    "firstName": "Jonas",
    "lastName": "Kovacs",
    "dateOfBirth": "2004-03-12",
    "address": {
      "street": "53 Alserbachstrasse",
      "city": "Vienna",
      "postalCode": "1030",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 84000,
    "creditScore": 533,
    "riskBand": "Very Poor"
  },
  "APP1023": {
    "applicantId": "APP1023",
    "ssn": "111-22-1023",
    "firstName": "Tom",
    "lastName": "Berger",
    "dateOfBirth": "1981-06-01",
    "address": {
      "street": "17 Taborstrasse",
      "city": "Vienna",
      "postalCode": "1100",
      "country": "AT"
    },
    "employmentStatus": "Self-Employed",
    "annualIncome": 92000,
    "creditScore": 586,
    "riskBand": "Poor"
  },
  "APP1024": {
    "applicantId": "APP1024",
    "ssn": "111-22-1024",
    "firstName": "Max",
    "lastName": "Pichler",
    "dateOfBirth": "1989-02-20",
    "address": {
      "street": "81 Westbahnstrasse",
      "city": "Vienna",
      "postalCode": "1060",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 137000,
    "creditScore": 698,
    "riskBand": "Fair"
  },
  "APP1025": {
    "applicantId": "APP1025",
    "ssn": "111-22-1025",
    "firstName": "Sophie",
    "lastName": "Brunner",
    "dateOfBirth": "1995-04-21",
    "address": {
      "street": "43 Praterstrasse",
      "city": "Vienna",
      "postalCode": "1010",
      "country": "AT"
    },
    "employmentStatus": "Self-Employed",
    "annualIncome": 122000,
    "creditScore": 688,
    "riskBand": "Fair"
  },
  "APP1026": {
    "applicantId": "APP1026",
    "ssn": "111-22-1026",
    "firstName": "Michael",
    "lastName": "Kovacs",
    "dateOfBirth": "1995-03-13",
    "address": {
      "street": "54 Gumpendorfer Str",
      "city": "Vienna",
      "postalCode": "1060",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 137000,
    "creditScore": 673,
    "riskBand": "Fair"
  },
  "APP1027": {
    "applicantId": "APP1027",
    "ssn": "111-22-1027",
    "firstName": "David",
    "lastName": "Eder",
    "dateOfBirth": "1991-11-23",
    "address": {
      "street": "23 Hauptstrasse",
      "city": "Vienna",
      "postalCode": "1090",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 51000,
    "creditScore": 596,
    "riskBand": "Poor"
  },
  "APP1028": {
    "applicantId": "APP1028",
    "ssn": "111-22-1028",
    "firstName": "Clara",
    "lastName": "Koller",
    "dateOfBirth": "1997-02-27",
    "address": {
      "street": "95 Hauptstrasse",
      "city": "Vienna",
      "postalCode": "1090",
      "country": "AT"
    },
    "employmentStatus": "Self-Employed",
    "annualIncome": 64000,
    "creditScore": 583,
    "riskBand": "Poor"
  },
  "APP1029": {
    "applicantId": "APP1029",
    "ssn": "111-22-1029",
    "firstName": "Stefan",
    "lastName": "Wagner",
    "dateOfBirth": "1979-10-16",
    "address": {
      "street": "29 Landstrasser Hauptstr",
      "city": "Vienna",
      "postalCode": "1010",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 113000,
    "creditScore": 706,
    "riskBand": "Good"
  },
  "APP1030": {
    "applicantId": "APP1030",
    "ssn": "111-22-1030",
    "firstName": "Tom",
    "lastName": "Wagner",
    "dateOfBirth": "1965-02-20",
    "address": {
      "street": "94 Mariahilfer Str",
      "city": "Vienna",
      "postalCode": "1030",
      "country": "AT"
    },
    "employmentStatus": "Unemployed",
    "annualIncome": 0,
    "creditScore": 536,
    "riskBand": "Very Poor"
  },
  "APP1031": {
    "applicantId": "APP1031",
    "ssn": "111-22-1031",
    "firstName": "Michael",
    "lastName": "Pichler",
    "dateOfBirth": "1983-04-06",
    "address": {
      "street": "18 Favoritenstrasse",
      "city": "Vienna",
      "postalCode": "1100",
      "country": "AT"
    },
    "employmentStatus": "Self-Employed",
    "annualIncome": 47000,
    "creditScore": 659,
    "riskBand": "Fair"
  },
  "APP1032": {
    "applicantId": "APP1032",
    "ssn": "111-22-1032",
    "firstName": "Jonas",
    "lastName": "Weber",
    "dateOfBirth": "1986-02-01",
    "address": {
      "street": "43 Gumpendorfer Str",
      "city": "Vienna",
      "postalCode": "1010",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 55000,
    "creditScore": 524,
    "riskBand": "Very Poor"
  },
  "APP1033": {
    "applicantId": "APP1033",
    "ssn": "111-22-1033",
    "firstName": "Lena",
    "lastName": "Schmid",
    "dateOfBirth": "1970-06-14",
    "address": {
      "street": "42 Westbahnstrasse",
      "city": "Vienna",
      "postalCode": "1100",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 65000,
    "creditScore": 525,
    "riskBand": "Very Poor"
  },
  "APP1034": {
    "applicantId": "APP1034",
    "ssn": "111-22-1034",
    "firstName": "David",
    "lastName": "Wolf",
    "dateOfBirth": "1972-03-25",
    "address": {
      "street": "41 Hauptstrasse",
      "city": "Vienna",
      "postalCode": "1070",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 139000,
    "creditScore": 687,
    "riskBand": "Fair"
  },
  "APP1035": {
    "applicantId": "APP1035",
    "ssn": "111-22-1035",
    "firstName": "Laura",
    "lastName": "Brunner",
    "dateOfBirth": "1969-04-04",
    "address": {
      "street": "53 Gumpendorfer Str",
      "city": "Vienna",
      "postalCode": "1090",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 138000,
    "creditScore": 556,
    "riskBand": "Very Poor"
  },
  "APP1036": {
    "applicantId": "APP1036",
    "ssn": "111-22-1036",
    "firstName": "Michael",
    "lastName": "Steiner",
    "dateOfBirth": "1990-03-05",
    "address": {
      "street": "71 Ringstrasse",
      "city": "Vienna",
      "postalCode": "1090",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 86000,
    "creditScore": 684,
    "riskBand": "Fair"
  },
  "APP1037": {
    "applicantId": "APP1037",
    "ssn": "111-22-1037",
    "firstName": "Hannah",
    "lastName": "Lang",
    "dateOfBirth": "1991-12-25",
    "address": {
      "street": "61 Neubaugasse",
      "city": "Vienna",
      "postalCode": "1100",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 70000,
    "creditScore": 681,
    "riskBand": "Fair"
  },
  "APP1038": {
    "applicantId": "APP1038",
    "ssn": "111-22-1038",
    "firstName": "Lena",
    "lastName": "Leitner",
    "dateOfBirth": "1999-04-10",
    "address": {
      "street": "57 Ringstrasse",
      "city": "Vienna",
      "postalCode": "1010",
      "country": "AT"
    },
    "employmentStatus": "Self-Employed",
    "annualIncome": 74000,
    "creditScore": 554,
    "riskBand": "Very Poor"
  },
  "APP1039": {
    "applicantId": "APP1039",
    "ssn": "111-22-1039",
    "firstName": "Laura",
    "lastName": "Weber",
    "dateOfBirth": "2001-06-21",
    "address": {
      "street": "44 Schoenbrunner Str",
      "city": "Vienna",
      "postalCode": "1010",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 135000,
    "creditScore": 561,
    "riskBand": "Very Poor"
  },
  "APP1040": {
    "applicantId": "APP1040",
    "ssn": "111-22-1040",
    "firstName": "Julia",
    "lastName": "Huber",
    "dateOfBirth": "1966-03-05",
    "address": {
      "street": "6 Alserbachstrasse",
      "city": "Vienna",
      "postalCode": "1010",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 32000,
    "creditScore": 623,
    "riskBand": "Poor"
  },
  "APP1041": {
    "applicantId": "APP1041",
    "ssn": "111-22-1041",
    "firstName": "Elena",
    "lastName": "Maier",
    "dateOfBirth": "1985-11-21",
    "address": {
      "street": "73 Mariahilfer Str",
      "city": "Vienna",
      "postalCode": "1090",
      "country": "AT"
    },
    "employmentStatus": "Unemployed",
    "annualIncome": 0,
    "creditScore": 459,
    "riskBand": "Very Poor"
  },
  "APP1042": {
    "applicantId": "APP1042",
    "ssn": "111-22-1042",
    "firstName": "Eva",
    "lastName": "Leitner",
    "dateOfBirth": "1993-06-04",
    "address": {
      "street": "45 Schoenbrunner Str",
      "city": "Vienna",
      "postalCode": "1200",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 137000,
    "creditScore": 622,
    "riskBand": "Poor"
  },
  "APP1043": {
    "applicantId": "APP1043",
    "ssn": "111-22-1043",
    "firstName": "Maria",
    "lastName": "Brunner",
    "dateOfBirth": "1991-06-08",
    "address": {
      "street": "43 Hauptstrasse",
      "city": "Vienna",
      "postalCode": "1090",
      "country": "AT"
    },
    "employmentStatus": "Unemployed",
    "annualIncome": 0,
    "creditScore": 472,
    "riskBand": "Very Poor"
  },
  "APP1044": {
    "applicantId": "APP1044",
    "ssn": "111-22-1044",
    "firstName": "David",
    "lastName": "Leitner",
    "dateOfBirth": "1978-06-23",
    "address": {
      "street": "37 Schoenbrunner Str",
      "city": "Vienna",
      "postalCode": "1100",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 117000,
    "creditScore": 616,
    "riskBand": "Poor"
  },
  "APP1045": {
    "applicantId": "APP1045",
    "ssn": "111-22-1045",
    "firstName": "Lena",
    "lastName": "Steiner",
    "dateOfBirth": "1969-07-01",
    "address": {
      "street": "63 Favoritenstrasse",
      "city": "Vienna",
      "postalCode": "1030",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 86000,
    "creditScore": 535,
    "riskBand": "Very Poor"
  },
  "APP1046": {
    "applicantId": "APP1046",
    "ssn": "111-22-1046",
    "firstName": "Stefan",
    "lastName": "Eder",
    "dateOfBirth": "2004-09-22",
    "address": {
      "street": "24 Hauptstrasse",
      "city": "Vienna",
      "postalCode": "1010",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 130000,
    "creditScore": 601,
    "riskBand": "Poor"
  },
  "APP1047": {
    "applicantId": "APP1047",
    "ssn": "111-22-1047",
    "firstName": "Felix",
    "lastName": "Brunner",
    "dateOfBirth": "1983-02-07",
    "address": {
      "street": "54 Alserbachstrasse",
      "city": "Vienna",
      "postalCode": "1020",
      "country": "AT"
    },
    "employmentStatus": "Self-Employed",
    "annualIncome": 57000,
    "creditScore": 563,
    "riskBand": "Very Poor"
  },
  "APP1048": {
    "applicantId": "APP1048",
    "ssn": "111-22-1048",
    "firstName": "Lukas",
    "lastName": "Lang",
    "dateOfBirth": "2002-04-08",
    "address": {
      "street": "28 Favoritenstrasse",
      "city": "Vienna",
      "postalCode": "1090",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 63000,
    "creditScore": 578,
    "riskBand": "Very Poor"
  },
  "APP1049": {
    "applicantId": "APP1049",
    "ssn": "111-22-1049",
    "firstName": "Anna",
    "lastName": "Leitner",
    "dateOfBirth": "1994-03-02",
    "address": {
      "street": "20 Westbahnstrasse",
      "city": "Vienna",
      "postalCode": "1200",
      "country": "AT"
    },
    "employmentStatus": "Unemployed",
    "annualIncome": 0,
    "creditScore": 410,
    "riskBand": "Very Poor"
  },
  "APP1050": {
    "applicantId": "APP1050",
    "ssn": "111-22-1050",
    "firstName": "Paul",
    "lastName": "Fischer",
    "dateOfBirth": "1994-06-09",
    "address": {
      "street": "54 Schoenbrunner Str",
      "city": "Vienna",
      "postalCode": "1030",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 96000,
    "creditScore": 548,
    "riskBand": "Very Poor"
  },
  "APP1051": {
    "applicantId": "APP1051",
    "ssn": "111-22-1051",
    "firstName": "Hannah",
    "lastName": "Eder",
    "dateOfBirth": "1999-07-04",
    "address": {
      "street": "53 Neubaugasse",
      "city": "Vienna",
      "postalCode": "1020",
      "country": "AT"
    },
    "employmentStatus": "Unemployed",
    "annualIncome": 0,
    "creditScore": 567,
    "riskBand": "Very Poor"
  },
  "APP1052": {
    "applicantId": "APP1052",
    "ssn": "111-22-1052",
    "firstName": "Stefan",
    "lastName": "Steiner",
    "dateOfBirth": "2002-08-16",
    "address": {
      "street": "40 Gumpendorfer Str",
      "city": "Vienna",
      "postalCode": "1120",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 138000,
    "creditScore": 627,
    "riskBand": "Poor"
  },
  "APP1053": {
    "applicantId": "APP1053",
    "ssn": "111-22-1053",
    "firstName": "Daniel",
    "lastName": "Wagner",
    "dateOfBirth": "1996-01-09",
    "address": {
      "street": "71 Landstrasser Hauptstr",
      "city": "Vienna",
      "postalCode": "1070",
      "country": "AT"
    },
    "employmentStatus": "Self-Employed",
    "annualIncome": 88000,
    "creditScore": 670,
    "riskBand": "Fair"
  },
  "APP1054": {
    "applicantId": "APP1054",
    "ssn": "111-22-1054",
    "firstName": "Felix",
    "lastName": "Wolf",
    "dateOfBirth": "1988-05-23",
    "address": {
      "street": "88 Schoenbrunner Str",
      "city": "Vienna",
      "postalCode": "1030",
      "country": "AT"
    },
    "employmentStatus": "Self-Employed",
    "annualIncome": 29000,
    "creditScore": 499,
    "riskBand": "Very Poor"
  },
  "APP1055": {
    "applicantId": "APP1055",
    "ssn": "111-22-1055",
    "firstName": "Max",
    "lastName": "Pichler",
    "dateOfBirth": "1971-05-20",
    "address": {
      "street": "63 Neubaugasse",
      "city": "Vienna",
      "postalCode": "1200",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 97000,
    "creditScore": 594,
    "riskBand": "Poor"
  },
  "APP1056": {
    "applicantId": "APP1056",
    "ssn": "111-22-1056",
    "firstName": "David",
    "lastName": "Berger",
    "dateOfBirth": "1980-03-19",
    "address": {
      "street": "71 Ringstrasse",
      "city": "Vienna",
      "postalCode": "1060",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 140000,
    "creditScore": 653,
    "riskBand": "Fair"
  },
  "APP1057": {
    "applicantId": "APP1057",
    "ssn": "111-22-1057",
    "firstName": "Sarah",
    "lastName": "Steiner",
    "dateOfBirth": "1980-04-01",
    "address": {
      "street": "10 Schoenbrunner Str",
      "city": "Vienna",
      "postalCode": "1100",
      "country": "AT"
    },
    "employmentStatus": "Unemployed",
    "annualIncome": 0,
    "creditScore": 555,
    "riskBand": "Very Poor"
  },
  "APP1058": {
    "applicantId": "APP1058",
    "ssn": "111-22-1058",
    "firstName": "Anna",
    "lastName": "Lang",
    "dateOfBirth": "1997-12-11",
    "address": {
      "street": "26 Landstrasser Hauptstr",
      "city": "Vienna",
      "postalCode": "1060",
      "country": "AT"
    },
    "employmentStatus": "Self-Employed",
    "annualIncome": 34000,
    "creditScore": 631,
    "riskBand": "Poor"
  },
  "APP1059": {
    "applicantId": "APP1059",
    "ssn": "111-22-1059",
    "firstName": "Lena",
    "lastName": "Berger",
    "dateOfBirth": "1981-10-12",
    "address": {
      "street": "28 Gumpendorfer Str",
      "city": "Vienna",
      "postalCode": "1070",
      "country": "AT"
    },
    "employmentStatus": "Unemployed",
    "annualIncome": 0,
    "creditScore": 543,
    "riskBand": "Very Poor"
  },
  "APP1060": {
    "applicantId": "APP1060",
    "ssn": "111-22-1060",
    "firstName": "Tom",
    "lastName": "Fischer",
    "dateOfBirth": "1980-06-01",
    "address": {
      "street": "58 Westbahnstrasse",
      "city": "Vienna",
      "postalCode": "1070",
      "country": "AT"
    },
    "employmentStatus": "Unemployed",
    "annualIncome": 0,
    "creditScore": 485,
    "riskBand": "Very Poor"
  },
  "APP1061": {
    "applicantId": "APP1061",
    "ssn": "111-22-1061",
    "firstName": "Clara",
    "lastName": "Maier",
    "dateOfBirth": "2002-05-04",
    "address": {
      "street": "75 Praterstrasse",
      "city": "Vienna",
      "postalCode": "1030",
      "country": "AT"
    },
    "employmentStatus": "Unemployed",
    "annualIncome": 0,
    "creditScore": 499,
    "riskBand": "Very Poor"
  },
  "APP1062": {
    "applicantId": "APP1062",
    "ssn": "111-22-1062",
    "firstName": "Tom",
    "lastName": "Brunner",
    "dateOfBirth": "1981-11-05",
    "address": {
      "street": "35 Taborstrasse",
      "city": "Vienna",
      "postalCode": "1060",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 68000,
    "creditScore": 597,
    "riskBand": "Poor"
  },
  "APP1063": {
    "applicantId": "APP1063",
    "ssn": "111-22-1063",
    "firstName": "Anna",
    "lastName": "Gruber",
    "dateOfBirth": "1972-07-22",
    "address": {
      "street": "13 Mariahilfer Str",
      "city": "Vienna",
      "postalCode": "1100",
      "country": "AT"
    },
    "employmentStatus": "Unemployed",
    "annualIncome": 0,
    "creditScore": 490,
    "riskBand": "Very Poor"
  },
  "APP1064": {
    "applicantId": "APP1064",
    "ssn": "111-22-1064",
    "firstName": "Sarah",
    "lastName": "Huber",
    "dateOfBirth": "1991-03-23",
    "address": {
      "street": "90 Favoritenstrasse",
      "city": "Vienna",
      "postalCode": "1060",
      "country": "AT"
    },
    "employmentStatus": "Unemployed",
    "annualIncome": 0,
    "creditScore": 456,
    "riskBand": "Very Poor"
  },
  "APP1065": {
    "applicantId": "APP1065",
    "ssn": "111-22-1065",
    "firstName": "Elena",
    "lastName": "Lang",
    "dateOfBirth": "1979-03-19",
    "address": {
      "street": "71 Schoenbrunner Str",
      "city": "Vienna",
      "postalCode": "1100",
      "country": "AT"
    },
    "employmentStatus": "Unemployed",
    "annualIncome": 0,
    "creditScore": 535,
    "riskBand": "Very Poor"
  },
  "APP1066": {
    "applicantId": "APP1066",
    "ssn": "111-22-1066",
    "firstName": "Sarah",
    "lastName": "Koller",
    "dateOfBirth": "2002-07-12",
    "address": {
      "street": "68 Taborstrasse",
      "city": "Vienna",
      "postalCode": "1020",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 105000,
    "creditScore": 560,
    "riskBand": "Very Poor"
  },
  "APP1067": {
    "applicantId": "APP1067",
    "ssn": "111-22-1067",
    "firstName": "David",
    "lastName": "Pichler",
    "dateOfBirth": "2003-11-18",
    "address": {
      "street": "75 Favoritenstrasse",
      "city": "Vienna",
      "postalCode": "1060",
      "country": "AT"
    },
    "employmentStatus": "Self-Employed",
    "annualIncome": 107000,
    "creditScore": 582,
    "riskBand": "Poor"
  },
  "APP1068": {
    "applicantId": "APP1068",
    "ssn": "111-22-1068",
    "firstName": "Tom",
    "lastName": "Schmid",
    "dateOfBirth": "1995-04-23",
    "address": {
      "street": "40 Landstrasser Hauptstr",
      "city": "Vienna",
      "postalCode": "1100",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 48000,
    "creditScore": 642,
    "riskBand": "Poor"
  },
  "APP1069": {
    "applicantId": "APP1069",
    "ssn": "111-22-1069",
    "firstName": "Anna",
    "lastName": "Bauer",
    "dateOfBirth": "1997-02-12",
    "address": {
      "street": "38 Taborstrasse",
      "city": "Vienna",
      "postalCode": "1150",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 110000,
    "creditScore": 665,
    "riskBand": "Fair"
  },
  "APP1070": {
    "applicantId": "APP1070",
    "ssn": "111-22-1070",
    "firstName": "Eva",
    "lastName": "Maier",
    "dateOfBirth": "1966-02-09",
    "address": {
      "street": "62 Neubaugasse",
      "city": "Vienna",
      "postalCode": "1100",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 113000,
    "creditScore": 698,
    "riskBand": "Fair"
  },
  "APP1071": {
    "applicantId": "APP1071",
    "ssn": "111-22-1071",
    "firstName": "Lena",
    "lastName": "Kovacs",
    "dateOfBirth": "1989-04-05",
    "address": {
      "street": "18 Westbahnstrasse",
      "city": "Vienna",
      "postalCode": "1020",
      "country": "AT"
    },
    "employmentStatus": "Unemployed",
    "annualIncome": 0,
    "creditScore": 518,
    "riskBand": "Very Poor"
  },
  "APP1072": {
    "applicantId": "APP1072",
    "ssn": "111-22-1072",
    "firstName": "Anna",
    "lastName": "Eder",
    "dateOfBirth": "2003-08-13",
    "address": {
      "street": "16 Neubaugasse",
      "city": "Vienna",
      "postalCode": "1030",
      "country": "AT"
    },
    "employmentStatus": "Unemployed",
    "annualIncome": 0,
    "creditScore": 485,
    "riskBand": "Very Poor"
  },
  "APP1073": {
    "applicantId": "APP1073",
    "ssn": "111-22-1073",
    "firstName": "Daniel",
    "lastName": "Wolf",
    "dateOfBirth": "1987-12-13",
    "address": {
      "street": "15 Alserbachstrasse",
      "city": "Vienna",
      "postalCode": "1150",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 28000,
    "creditScore": 560,
    "riskBand": "Very Poor"
  },
  "APP1074": {
    "applicantId": "APP1074",
    "ssn": "111-22-1074",
    "firstName": "Laura",
    "lastName": "Bauer",
    "dateOfBirth": "1973-09-19",
    "address": {
      "street": "78 Alserbachstrasse",
      "city": "Vienna",
      "postalCode": "1200",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 117000,
    "creditScore": 583,
    "riskBand": "Poor"
  },
  "APP1075": {
    "applicantId": "APP1075",
    "ssn": "111-22-1075",
    "firstName": "Peter",
    "lastName": "Koller",
    "dateOfBirth": "1996-08-11",
    "address": {
      "street": "73 Neubaugasse",
      "city": "Vienna",
      "postalCode": "1070",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 124000,
    "creditScore": 548,
    "riskBand": "Very Poor"
  },
  "APP1076": {
    "applicantId": "APP1076",
    "ssn": "111-22-1076",
    "firstName": "Laura",
    "lastName": "Gruber",
    "dateOfBirth": "1996-03-04",
    "address": {
      "street": "22 Favoritenstrasse",
      "city": "Vienna",
      "postalCode": "1030",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 55000,
    "creditScore": 619,
    "riskBand": "Poor"
  },
  "APP1077": {
    "applicantId": "APP1077",
    "ssn": "111-22-1077",
    "firstName": "Paul",
    "lastName": "Novak",
    "dateOfBirth": "1974-08-24",
    "address": {
      "street": "12 Hauptstrasse",
      "city": "Vienna",
      "postalCode": "1060",
      "country": "AT"
    },
    "employmentStatus": "Self-Employed",
    "annualIncome": 68000,
    "creditScore": 640,
    "riskBand": "Poor"
  },
  "APP1078": {
    "applicantId": "APP1078",
    "ssn": "111-22-1078",
    "firstName": "Elena",
    "lastName": "Bauer",
    "dateOfBirth": "1988-04-15",
    "address": {
      "street": "9 Westbahnstrasse",
      "city": "Vienna",
      "postalCode": "1200",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 101000,
    "creditScore": 665,
    "riskBand": "Fair"
  },
  "APP1079": {
    "applicantId": "APP1079",
    "ssn": "111-22-1079",
    "firstName": "Max",
    "lastName": "Leitner",
    "dateOfBirth": "1978-10-18",
    "address": {
      "street": "45 Mariahilfer Str",
      "city": "Vienna",
      "postalCode": "1120",
      "country": "AT"
    },
    "employmentStatus": "Self-Employed",
    "annualIncome": 116000,
    "creditScore": 701,
    "riskBand": "Good"
  },
  "APP1080": {
    "applicantId": "APP1080",
    "ssn": "111-22-1080",
    "firstName": "David",
    "lastName": "Koller",
    "dateOfBirth": "1991-04-28",
    "address": {
      "street": "92 Neubaugasse",
      "city": "Vienna",
      "postalCode": "1090",
      "country": "AT"
    },
    "employmentStatus": "Unemployed",
    "annualIncome": 0,
    "creditScore": 439,
    "riskBand": "Very Poor"
  },
  "APP1081": {
    "applicantId": "APP1081",
    "ssn": "111-22-1081",
    "firstName": "Sarah",
    "lastName": "Berger",
    "dateOfBirth": "2001-08-08",
    "address": {
      "street": "19 Hauptstrasse",
      "city": "Vienna",
      "postalCode": "1020",
      "country": "AT"
    },
    "employmentStatus": "Unemployed",
    "annualIncome": 0,
    "creditScore": 546,
    "riskBand": "Very Poor"
  },
  "APP1082": {
    "applicantId": "APP1082",
    "ssn": "111-22-1082",
    "firstName": "Nina",
    "lastName": "Winkler",
    "dateOfBirth": "1965-10-14",
    "address": {
      "street": "49 Westbahnstrasse",
      "city": "Vienna",
      "postalCode": "1120",
      "country": "AT"
    },
    "employmentStatus": "Self-Employed",
    "annualIncome": 36000,
    "creditScore": 607,
    "riskBand": "Poor"
  },
  "APP1083": {
    "applicantId": "APP1083",
    "ssn": "111-22-1083",
    "firstName": "Elena",
    "lastName": "Maier",
    "dateOfBirth": "1993-10-28",
    "address": {
      "street": "29 Neubaugasse",
      "city": "Vienna",
      "postalCode": "1010",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 84000,
    "creditScore": 587,
    "riskBand": "Poor"
  },
  "APP1084": {
    "applicantId": "APP1084",
    "ssn": "111-22-1084",
    "firstName": "Daniel",
    "lastName": "Novak",
    "dateOfBirth": "1991-09-12",
    "address": {
      "street": "1 Hauptstrasse",
      "city": "Vienna",
      "postalCode": "1030",
      "country": "AT"
    },
    "employmentStatus": "Self-Employed",
    "annualIncome": 73000,
    "creditScore": 636,
    "riskBand": "Poor"
  },
  "APP1085": {
    "applicantId": "APP1085",
    "ssn": "111-22-1085",
    "firstName": "Sarah",
    "lastName": "Weber",
    "dateOfBirth": "1974-08-11",
    "address": {
      "street": "37 Favoritenstrasse",
      "city": "Vienna",
      "postalCode": "1150",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 100000,
    "creditScore": 638,
    "riskBand": "Poor"
  },
  "APP1086": {
    "applicantId": "APP1086",
    "ssn": "111-22-1086",
    "firstName": "Maria",
    "lastName": "Winkler",
    "dateOfBirth": "1967-11-17",
    "address": {
      "street": "79 Taborstrasse",
      "city": "Vienna",
      "postalCode": "1020",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 125000,
    "creditScore": 562,
    "riskBand": "Very Poor"
  },
  "APP1087": {
    "applicantId": "APP1087",
    "ssn": "111-22-1087",
    "firstName": "Peter",
    "lastName": "Kovacs",
    "dateOfBirth": "2001-03-16",
    "address": {
      "street": "51 Landstrasser Hauptstr",
      "city": "Vienna",
      "postalCode": "1100",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 119000,
    "creditScore": 647,
    "riskBand": "Poor"
  },
  "APP1088": {
    "applicantId": "APP1088",
    "ssn": "111-22-1088",
    "firstName": "Peter",
    "lastName": "Bauer",
    "dateOfBirth": "1978-01-14",
    "address": {
      "street": "13 Landstrasser Hauptstr",
      "city": "Vienna",
      "postalCode": "1120",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 37000,
    "creditScore": 527,
    "riskBand": "Very Poor"
  },
  "APP1089": {
    "applicantId": "APP1089",
    "ssn": "111-22-1089",
    "firstName": "Nina",
    "lastName": "Fischer",
    "dateOfBirth": "1976-06-19",
    "address": {
      "street": "42 Hauptstrasse",
      "city": "Vienna",
      "postalCode": "1100",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 140000,
    "creditScore": 584,
    "riskBand": "Poor"
  },
  "APP1090": {
    "applicantId": "APP1090",
    "ssn": "111-22-1090",
    "firstName": "Jonas",
    "lastName": "Winkler",
    "dateOfBirth": "1982-11-09",
    "address": {
      "street": "61 Gumpendorfer Str",
      "city": "Vienna",
      "postalCode": "1090",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 79000,
    "creditScore": 633,
    "riskBand": "Poor"
  },
  "APP1091": {
    "applicantId": "APP1091",
    "ssn": "111-22-1091",
    "firstName": "Peter",
    "lastName": "Wolf",
    "dateOfBirth": "1995-01-15",
    "address": {
      "street": "32 Neubaugasse",
      "city": "Vienna",
      "postalCode": "1200",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 126000,
    "creditScore": 657,
    "riskBand": "Fair"
  },
  "APP1092": {
    "applicantId": "APP1092",
    "ssn": "111-22-1092",
    "firstName": "Max",
    "lastName": "Maier",
    "dateOfBirth": "1975-11-14",
    "address": {
      "street": "53 Schoenbrunner Str",
      "city": "Vienna",
      "postalCode": "1120",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 49000,
    "creditScore": 576,
    "riskBand": "Very Poor"
  },
  "APP1093": {
    "applicantId": "APP1093",
    "ssn": "111-22-1093",
    "firstName": "Elena",
    "lastName": "Novak",
    "dateOfBirth": "2003-01-14",
    "address": {
      "street": "64 Alserbachstrasse",
      "city": "Vienna",
      "postalCode": "1090",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 100000,
    "creditScore": 687,
    "riskBand": "Fair"
  },
  "APP1094": {
    "applicantId": "APP1094",
    "ssn": "111-22-1094",
    "firstName": "David",
    "lastName": "Schmid",
    "dateOfBirth": "1965-06-14",
    "address": {
      "street": "46 Hauptstrasse",
      "city": "Vienna",
      "postalCode": "1090",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 55000,
    "creditScore": 599,
    "riskBand": "Poor"
  },
  "APP1095": {
    "applicantId": "APP1095",
    "ssn": "111-22-1095",
    "firstName": "Eva",
    "lastName": "Pichler",
    "dateOfBirth": "1997-10-16",
    "address": {
      "street": "89 Hauptstrasse",
      "city": "Vienna",
      "postalCode": "1010",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 134000,
    "creditScore": 599,
    "riskBand": "Poor"
  },
  "APP1096": {
    "applicantId": "APP1096",
    "ssn": "111-22-1096",
    "firstName": "Lena",
    "lastName": "Maier",
    "dateOfBirth": "1983-05-25",
    "address": {
      "street": "54 Ringstrasse",
      "city": "Vienna",
      "postalCode": "1020",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 113000,
    "creditScore": 553,
    "riskBand": "Very Poor"
  },
  "APP1097": {
    "applicantId": "APP1097",
    "ssn": "111-22-1097",
    "firstName": "Julia",
    "lastName": "Maier",
    "dateOfBirth": "1991-12-01",
    "address": {
      "street": "1 Praterstrasse",
      "city": "Vienna",
      "postalCode": "1090",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 100000,
    "creditScore": 606,
    "riskBand": "Poor"
  },
  "APP1098": {
    "applicantId": "APP1098",
    "ssn": "111-22-1098",
    "firstName": "Lena",
    "lastName": "Schmid",
    "dateOfBirth": "1972-02-19",
    "address": {
      "street": "74 Alserbachstrasse",
      "city": "Vienna",
      "postalCode": "1100",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 127000,
    "creditScore": 583,
    "riskBand": "Poor"
  },
  "APP1099": {
    "applicantId": "APP1099",
    "ssn": "111-22-1099",
    "firstName": "Daniel",
    "lastName": "Gruber",
    "dateOfBirth": "1992-05-01",
    "address": {
      "street": "30 Mariahilfer Str",
      "city": "Vienna",
      "postalCode": "1020",
      "country": "AT"
    },
    "employmentStatus": "Unemployed",
    "annualIncome": 0,
    "creditScore": 501,
    "riskBand": "Very Poor"
  },
  "APP1100": {
    "applicantId": "APP1100",
    "ssn": "111-22-1100",
    "firstName": "Julia",
    "lastName": "Eder",
    "dateOfBirth": "1978-06-15",
    "address": {
      "street": "13 Landstrasser Hauptstr",
      "city": "Vienna",
      "postalCode": "1120",
      "country": "AT"
    },
    "employmentStatus": "Employed",
    "annualIncome": 87000,
    "creditScore": 666,
    "riskBand": "Fair"
  }
};

module.exports = { applicants };
