// AUTO-GENERATED by scripts/generate-mcn-data.js — do not hand-edit.
// Regenerate with: node scripts/generate-mcn-data.js
//
// Seeded member base for the Mobile Club Nord use case (Pega AI Week).
// 66 members, deterministic (fixed PRNG seed).
//
// Fixed test cases that the user stories and Cucumber scenarios rely on —
// these must stay stable across regenerations:
//   MCN-2023-000001  Dirk Dublettski — Löst bei POST /mitglieder immer 409 DUBLETTE aus (Nachname-Trigger).
//   MCN-2022-000002  Greta Beendet — Gekündigte Mitgliedschaft — für US 10 (Pannenmeldung ohne gültige Mitgliedschaft).
//   MCN-2021-000003  Ruth Ruhend — Ruhende Mitgliedschaft nach Zahlungsausfall — für US 15.
//   MCN-2024-000004  Famke Familjen — Familienmitgliedschaft mit drei zugeordneten Personen — für US 5 und US 13.
//   MCN-2025-000099  Karl Kartenstau — Mitgliedsnummer endet auf 99 — Kartenauftrag bleibt in IN_PRODUKTION (US 8, SLA-Test).
//   MCN-2025-000098  Sven Störfall — Mitgliedsnummer endet auf 98 — POST /kartenauftraege antwortet 503 (US 8).
//
// Plus deliberate name collisions (Anna Petersen x2, Lars Jansen x2) so the
// duplicate search returns medium-confidence matches.

const mitglieder = {
  "MCN-2023-000001": {
    "mitgliedsnummer": "MCN-2023-000001",
    "status": "Aktiv",
    "tarif": "Plus",
    "eintrittsdatum": "2023-05-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Dirk",
      "nachname": "Dublettski",
      "geburtsdatum": "1981-04-17",
      "email": "dirk.dublettski@example.de"
    },
    "adresse": {
      "strasse": "Osterstraße",
      "hausnummer": "14",
      "postleitzahl": "20249",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 18,
    "testhinweis": "Löst bei POST /mitglieder immer 409 DUBLETTE aus (Nachname-Trigger)."
  },
  "MCN-2022-000002": {
    "mitgliedsnummer": "MCN-2022-000002",
    "status": "Beendet",
    "tarif": "Basis",
    "eintrittsdatum": "2022-01-01",
    "zahlungsart": "Rechnung",
    "hauptmitglied": {
      "vorname": "Greta",
      "nachname": "Beendet",
      "geburtsdatum": "1969-11-02",
      "email": "greta.beendet@example.de"
    },
    "adresse": {
      "strasse": "Große Bergstraße",
      "hausnummer": "3",
      "postleitzahl": "22765",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 12,
    "testhinweis": "Gekündigte Mitgliedschaft — für US 10 (Pannenmeldung ohne gültige Mitgliedschaft)."
  },
  "MCN-2021-000003": {
    "mitgliedsnummer": "MCN-2021-000003",
    "status": "Ruhend",
    "tarif": "Plus",
    "eintrittsdatum": "2021-09-15",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Ruth",
      "nachname": "Ruhend",
      "geburtsdatum": "1988-07-23",
      "email": "ruth.ruhend@example.de"
    },
    "adresse": {
      "strasse": "Barmbeker Markt",
      "hausnummer": "9",
      "postleitzahl": "22089",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 18,
    "testhinweis": "Ruhende Mitgliedschaft nach Zahlungsausfall — für US 15."
  },
  "MCN-2024-000004": {
    "mitgliedsnummer": "MCN-2024-000004",
    "status": "Aktiv",
    "tarif": "Plus",
    "eintrittsdatum": "2024-03-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Famke",
      "nachname": "Familjen",
      "geburtsdatum": "1985-02-11",
      "email": "famke.familjen@example.de"
    },
    "adresse": {
      "strasse": "Mühlenkamp",
      "hausnummer": "17",
      "postleitzahl": "22303",
      "ort": "Hamburg"
    },
    "familienmitglieder": [
      {
        "vorname": "Bo",
        "nachname": "Familjen",
        "geburtsdatum": "1983-06-30",
        "beziehung": "Partner",
        "altersklasse": "Erwachsener"
      },
      {
        "vorname": "Mia",
        "nachname": "Familjen",
        "geburtsdatum": "2012-04-08",
        "beziehung": "Kind",
        "altersklasse": "Kind"
      },
      {
        "vorname": "Tjark",
        "nachname": "Familjen",
        "geburtsdatum": "2016-09-19",
        "beziehung": "Kind",
        "altersklasse": "Kind"
      }
    ],
    "monatsbeitrag": 36,
    "testhinweis": "Familienmitgliedschaft mit drei zugeordneten Personen — für US 5 und US 13."
  },
  "MCN-2025-000099": {
    "mitgliedsnummer": "MCN-2025-000099",
    "status": "Aktiv",
    "tarif": "Basis",
    "eintrittsdatum": "2025-02-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Karl",
      "nachname": "Kartenstau",
      "geburtsdatum": "1976-12-05",
      "email": "karl.kartenstau@example.de"
    },
    "adresse": {
      "strasse": "Winterhuder Weg",
      "hausnummer": "41",
      "postleitzahl": "21073",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 12,
    "testhinweis": "Mitgliedsnummer endet auf 99 — Kartenauftrag bleibt in IN_PRODUKTION (US 8, SLA-Test)."
  },
  "MCN-2025-000098": {
    "mitgliedsnummer": "MCN-2025-000098",
    "status": "Aktiv",
    "tarif": "Plus",
    "eintrittsdatum": "2025-06-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Sven",
      "nachname": "Störfall",
      "geburtsdatum": "1990-03-28",
      "email": "sven.stoerfall@example.de"
    },
    "adresse": {
      "strasse": "Holstenstraße",
      "hausnummer": "22",
      "postleitzahl": "24103",
      "ort": "Kiel"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 18,
    "testhinweis": "Mitgliedsnummer endet auf 98 — POST /kartenauftraege antwortet 503 (US 8)."
  },
  "MCN-2025-000101": {
    "mitgliedsnummer": "MCN-2025-000101",
    "status": "Aktiv",
    "tarif": "Basis",
    "eintrittsdatum": "2025-04-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Anna",
      "nachname": "Petersen",
      "geburtsdatum": "1999-12-06",
      "email": "anna.petersen@example.de"
    },
    "adresse": {
      "strasse": "Große Bergstraße",
      "hausnummer": "89",
      "postleitzahl": "22303",
      "ort": "Hamburg"
    },
    "familienmitglieder": [
      {
        "vorname": "Jonas",
        "nachname": "Petersen",
        "geburtsdatum": "1962-08-18",
        "beziehung": "Kind",
        "altersklasse": "Erwachsener"
      },
      {
        "vorname": "Broder",
        "nachname": "Petersen",
        "geburtsdatum": "1990-08-08",
        "beziehung": "Partnerin",
        "altersklasse": "Erwachsener"
      }
    ],
    "monatsbeitrag": 32
  },
  "MCN-2022-000102": {
    "mitgliedsnummer": "MCN-2022-000102",
    "status": "Aktiv",
    "tarif": "Basis",
    "eintrittsdatum": "2022-05-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Anna",
      "nachname": "Petersen",
      "geburtsdatum": "1996-06-09",
      "email": "anna.petersen@example.de"
    },
    "adresse": {
      "strasse": "Mühlenkamp",
      "hausnummer": "5",
      "postleitzahl": "20357",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 8
  },
  "MCN-2023-000103": {
    "mitgliedsnummer": "MCN-2023-000103",
    "status": "Aktiv",
    "tarif": "Plus",
    "eintrittsdatum": "2023-12-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Lars",
      "nachname": "Jansen",
      "geburtsdatum": "2005-09-23",
      "email": "lars.jansen@example.de"
    },
    "adresse": {
      "strasse": "Billstedter Hauptstraße",
      "hausnummer": "2",
      "postleitzahl": "22303",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 12
  },
  "MCN-2022-000104": {
    "mitgliedsnummer": "MCN-2022-000104",
    "status": "Ruhend",
    "tarif": "Basis",
    "eintrittsdatum": "2022-06-01",
    "zahlungsart": "Rechnung",
    "hauptmitglied": {
      "vorname": "Lars",
      "nachname": "Jansen",
      "geburtsdatum": "2003-05-02",
      "email": "lars.jansen@example.de"
    },
    "adresse": {
      "strasse": "Große Bergstraße",
      "hausnummer": "79",
      "postleitzahl": "22303",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 8
  },
  "MCN-2021-000105": {
    "mitgliedsnummer": "MCN-2021-000105",
    "status": "Aktiv",
    "tarif": "Plus",
    "eintrittsdatum": "2021-04-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Frauke",
      "nachname": "Petersen",
      "geburtsdatum": "1981-04-09",
      "email": "frauke.petersen@example.de"
    },
    "adresse": {
      "strasse": "Eppendorfer Landstraße",
      "hausnummer": "70",
      "postleitzahl": "22303",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 18
  },
  "MCN-2022-000106": {
    "mitgliedsnummer": "MCN-2022-000106",
    "status": "Ruhend",
    "tarif": "Basis",
    "eintrittsdatum": "2022-07-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Wiebke",
      "nachname": "Rohwedder",
      "geburtsdatum": "1956-12-07",
      "email": "wiebke.rohwedder@example.de"
    },
    "adresse": {
      "strasse": "Winterhuder Weg",
      "hausnummer": "41",
      "postleitzahl": "25524",
      "ort": "Itzehoe"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 12
  },
  "MCN-2019-000107": {
    "mitgliedsnummer": "MCN-2019-000107",
    "status": "Aktiv",
    "tarif": "Plus",
    "eintrittsdatum": "2019-05-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Svenja",
      "nachname": "Ketelsen",
      "geburtsdatum": "1965-01-21",
      "email": "svenja.ketelsen@example.de"
    },
    "adresse": {
      "strasse": "Alsterchaussee",
      "hausnummer": "83",
      "postleitzahl": "21682",
      "ort": "Stade"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 18
  },
  "MCN-2021-000108": {
    "mitgliedsnummer": "MCN-2021-000108",
    "status": "Aktiv",
    "tarif": "Plus",
    "eintrittsdatum": "2021-01-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Jonas",
      "nachname": "Wulff",
      "geburtsdatum": "1990-02-05",
      "email": "jonas.wulff@example.de"
    },
    "adresse": {
      "strasse": "Osterstraße",
      "hausnummer": "83",
      "postleitzahl": "22089",
      "ort": "Hamburg"
    },
    "familienmitglieder": [
      {
        "vorname": "Jannik",
        "nachname": "Wulff",
        "geburtsdatum": "1992-09-16",
        "beziehung": "Partnerin",
        "altersklasse": "Erwachsener"
      },
      {
        "vorname": "Heike",
        "nachname": "Wulff",
        "geburtsdatum": "1969-05-23",
        "beziehung": "Partner",
        "altersklasse": "Erwachsener"
      },
      {
        "vorname": "Imke",
        "nachname": "Wulff",
        "geburtsdatum": "2007-06-03",
        "beziehung": "Partner",
        "altersklasse": "Kind"
      }
    ],
    "monatsbeitrag": 54
  },
  "MCN-2022-000109": {
    "mitgliedsnummer": "MCN-2022-000109",
    "status": "Ruhend",
    "tarif": "Basis",
    "eintrittsdatum": "2022-08-01",
    "zahlungsart": "Rechnung",
    "hauptmitglied": {
      "vorname": "Jannik",
      "nachname": "Boysen",
      "geburtsdatum": "1990-10-14",
      "email": "jannik.boysen@example.de"
    },
    "adresse": {
      "strasse": "Billstedter Hauptstraße",
      "hausnummer": "45",
      "postleitzahl": "20249",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 12
  },
  "MCN-2024-000110": {
    "mitgliedsnummer": "MCN-2024-000110",
    "status": "Ruhend",
    "tarif": "Plus",
    "eintrittsdatum": "2024-05-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Svenja",
      "nachname": "Thomsen",
      "geburtsdatum": "1972-06-14",
      "email": "svenja.thomsen@example.de"
    },
    "adresse": {
      "strasse": "Große Bergstraße",
      "hausnummer": "77",
      "postleitzahl": "22089",
      "ort": "Hamburg"
    },
    "familienmitglieder": [
      {
        "vorname": "Anna",
        "nachname": "Thomsen",
        "geburtsdatum": "1961-03-26",
        "beziehung": "Kind",
        "altersklasse": "Erwachsener"
      }
    ],
    "monatsbeitrag": 36
  },
  "MCN-2021-000111": {
    "mitgliedsnummer": "MCN-2021-000111",
    "status": "Aktiv",
    "tarif": "Plus",
    "eintrittsdatum": "2021-12-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Mareike",
      "nachname": "Nissen",
      "geburtsdatum": "1956-09-20",
      "email": "mareike.nissen@example.de"
    },
    "adresse": {
      "strasse": "Lange Reihe",
      "hausnummer": "41",
      "postleitzahl": "22303",
      "ort": "Hamburg"
    },
    "familienmitglieder": [
      {
        "vorname": "Jonas",
        "nachname": "Nissen",
        "geburtsdatum": "2008-08-07",
        "beziehung": "Kind",
        "altersklasse": "Kind"
      }
    ],
    "monatsbeitrag": 18
  },
  "MCN-2022-000112": {
    "mitgliedsnummer": "MCN-2022-000112",
    "status": "Aktiv",
    "tarif": "Plus",
    "eintrittsdatum": "2022-10-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Broder",
      "nachname": "Momsen",
      "geburtsdatum": "1978-10-08",
      "email": "broder.momsen@example.de"
    },
    "adresse": {
      "strasse": "Barmbeker Markt",
      "hausnummer": "1",
      "postleitzahl": "21073",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 18
  },
  "MCN-2024-000113": {
    "mitgliedsnummer": "MCN-2024-000113",
    "status": "Aktiv",
    "tarif": "Basis",
    "eintrittsdatum": "2024-08-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Nils",
      "nachname": "Nissen",
      "geburtsdatum": "2002-10-20",
      "email": "nils.nissen@example.de"
    },
    "adresse": {
      "strasse": "Große Bergstraße",
      "hausnummer": "23",
      "postleitzahl": "21682",
      "ort": "Stade"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 8
  },
  "MCN-2021-000114": {
    "mitgliedsnummer": "MCN-2021-000114",
    "status": "Aktiv",
    "tarif": "Basis",
    "eintrittsdatum": "2021-07-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Nils",
      "nachname": "Boysen",
      "geburtsdatum": "1956-06-22",
      "email": "nils.boysen@example.de"
    },
    "adresse": {
      "strasse": "Große Bergstraße",
      "hausnummer": "53",
      "postleitzahl": "23552",
      "ort": "Lübeck"
    },
    "familienmitglieder": [
      {
        "vorname": "Broder",
        "nachname": "Boysen",
        "geburtsdatum": "1989-06-15",
        "beziehung": "Kind",
        "altersklasse": "Erwachsener"
      },
      {
        "vorname": "Silke",
        "nachname": "Boysen",
        "geburtsdatum": "1985-06-11",
        "beziehung": "Kind",
        "altersklasse": "Erwachsener"
      },
      {
        "vorname": "Nils",
        "nachname": "Boysen",
        "geburtsdatum": "2004-11-17",
        "beziehung": "Kind",
        "altersklasse": "Kind"
      }
    ],
    "monatsbeitrag": 36
  },
  "MCN-2024-000115": {
    "mitgliedsnummer": "MCN-2024-000115",
    "status": "Aktiv",
    "tarif": "Plus",
    "eintrittsdatum": "2024-06-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Silke",
      "nachname": "Jansen",
      "geburtsdatum": "1963-11-26",
      "email": "silke.jansen@example.de"
    },
    "adresse": {
      "strasse": "Alsterchaussee",
      "hausnummer": "114",
      "postleitzahl": "21073",
      "ort": "Hamburg"
    },
    "familienmitglieder": [
      {
        "vorname": "Jonas",
        "nachname": "Jansen",
        "geburtsdatum": "1994-04-18",
        "beziehung": "Kind",
        "altersklasse": "Erwachsener"
      }
    ],
    "monatsbeitrag": 36
  },
  "MCN-2019-000116": {
    "mitgliedsnummer": "MCN-2019-000116",
    "status": "Aktiv",
    "tarif": "Plus",
    "eintrittsdatum": "2019-04-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Lars",
      "nachname": "Thomsen",
      "geburtsdatum": "1956-03-23",
      "email": "lars.thomsen@example.de"
    },
    "adresse": {
      "strasse": "Rübenkamp",
      "hausnummer": "63",
      "postleitzahl": "21682",
      "ort": "Stade"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 18
  },
  "MCN-2019-000117": {
    "mitgliedsnummer": "MCN-2019-000117",
    "status": "Aktiv",
    "tarif": "Basis",
    "eintrittsdatum": "2019-10-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Wiebke",
      "nachname": "Ketelsen",
      "geburtsdatum": "1998-05-15",
      "email": "wiebke.ketelsen@example.de"
    },
    "adresse": {
      "strasse": "Lange Reihe",
      "hausnummer": "57",
      "postleitzahl": "21682",
      "ort": "Stade"
    },
    "familienmitglieder": [
      {
        "vorname": "Birte",
        "nachname": "Ketelsen",
        "geburtsdatum": "1990-12-05",
        "beziehung": "Partnerin",
        "altersklasse": "Erwachsener"
      }
    ],
    "monatsbeitrag": 20
  },
  "MCN-2025-000118": {
    "mitgliedsnummer": "MCN-2025-000118",
    "status": "Aktiv",
    "tarif": "Basis",
    "eintrittsdatum": "2025-01-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Svenja",
      "nachname": "Carstens",
      "geburtsdatum": "1996-10-09",
      "email": "svenja.carstens@example.de"
    },
    "adresse": {
      "strasse": "Fuhlsbüttler Straße",
      "hausnummer": "33",
      "postleitzahl": "22089",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 12
  },
  "MCN-2021-000119": {
    "mitgliedsnummer": "MCN-2021-000119",
    "status": "Aktiv",
    "tarif": "Basis",
    "eintrittsdatum": "2021-01-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Svenja",
      "nachname": "Rohwedder",
      "geburtsdatum": "1974-12-18",
      "email": "svenja.rohwedder@example.de"
    },
    "adresse": {
      "strasse": "Rübenkamp",
      "hausnummer": "110",
      "postleitzahl": "23552",
      "ort": "Lübeck"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 12
  },
  "MCN-2026-000120": {
    "mitgliedsnummer": "MCN-2026-000120",
    "status": "Aktiv",
    "tarif": "Plus",
    "eintrittsdatum": "2026-11-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Frauke",
      "nachname": "Timm",
      "geburtsdatum": "1997-03-09",
      "email": "frauke.timm@example.de"
    },
    "adresse": {
      "strasse": "Osterstraße",
      "hausnummer": "118",
      "postleitzahl": "22089",
      "ort": "Hamburg"
    },
    "familienmitglieder": [
      {
        "vorname": "Malte",
        "nachname": "Timm",
        "geburtsdatum": "1963-02-02",
        "beziehung": "Kind",
        "altersklasse": "Erwachsener"
      },
      {
        "vorname": "Hauke",
        "nachname": "Timm",
        "geburtsdatum": "2000-07-07",
        "beziehung": "Partner",
        "altersklasse": "Junger Erwachsener"
      }
    ],
    "monatsbeitrag": 48
  },
  "MCN-2024-000121": {
    "mitgliedsnummer": "MCN-2024-000121",
    "status": "Aktiv",
    "tarif": "Plus",
    "eintrittsdatum": "2024-01-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Imke",
      "nachname": "Clausen",
      "geburtsdatum": "1997-11-21",
      "email": "imke.clausen@example.de"
    },
    "adresse": {
      "strasse": "Rübenkamp",
      "hausnummer": "48",
      "postleitzahl": "23552",
      "ort": "Lübeck"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 12
  },
  "MCN-2026-000122": {
    "mitgliedsnummer": "MCN-2026-000122",
    "status": "Aktiv",
    "tarif": "Plus",
    "eintrittsdatum": "2026-12-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Heike",
      "nachname": "Bahnsen",
      "geburtsdatum": "1965-03-06",
      "email": "heike.bahnsen@example.de"
    },
    "adresse": {
      "strasse": "Große Bergstraße",
      "hausnummer": "13",
      "postleitzahl": "21073",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 18
  },
  "MCN-2020-000123": {
    "mitgliedsnummer": "MCN-2020-000123",
    "status": "Aktiv",
    "tarif": "Plus",
    "eintrittsdatum": "2020-04-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Ole",
      "nachname": "Jansen",
      "geburtsdatum": "1973-11-27",
      "email": "ole.jansen@example.de"
    },
    "adresse": {
      "strasse": "Mühlenkamp",
      "hausnummer": "43",
      "postleitzahl": "20249",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 18
  },
  "MCN-2025-000124": {
    "mitgliedsnummer": "MCN-2025-000124",
    "status": "Aktiv",
    "tarif": "Basis",
    "eintrittsdatum": "2025-09-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Malte",
      "nachname": "Lorenzen",
      "geburtsdatum": "2003-09-28",
      "email": "malte.lorenzen@example.de"
    },
    "adresse": {
      "strasse": "Billstedter Hauptstraße",
      "hausnummer": "14",
      "postleitzahl": "23552",
      "ort": "Lübeck"
    },
    "familienmitglieder": [
      {
        "vorname": "Birte",
        "nachname": "Lorenzen",
        "geburtsdatum": "1963-09-18",
        "beziehung": "Kind",
        "altersklasse": "Erwachsener"
      }
    ],
    "monatsbeitrag": 20
  },
  "MCN-2023-000125": {
    "mitgliedsnummer": "MCN-2023-000125",
    "status": "Aktiv",
    "tarif": "Plus",
    "eintrittsdatum": "2023-06-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Broder",
      "nachname": "Petersen",
      "geburtsdatum": "1959-04-04",
      "email": "broder.petersen@example.de"
    },
    "adresse": {
      "strasse": "Alsterchaussee",
      "hausnummer": "33",
      "postleitzahl": "22089",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 18
  },
  "MCN-2024-000126": {
    "mitgliedsnummer": "MCN-2024-000126",
    "status": "Ruhend",
    "tarif": "Plus",
    "eintrittsdatum": "2024-05-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Antje",
      "nachname": "Momsen",
      "geburtsdatum": "1968-06-12",
      "email": "antje.momsen@example.de"
    },
    "adresse": {
      "strasse": "Mühlenkamp",
      "hausnummer": "103",
      "postleitzahl": "25524",
      "ort": "Itzehoe"
    },
    "familienmitglieder": [
      {
        "vorname": "Antje",
        "nachname": "Momsen",
        "geburtsdatum": "1982-01-09",
        "beziehung": "Kind",
        "altersklasse": "Erwachsener"
      },
      {
        "vorname": "Frauke",
        "nachname": "Momsen",
        "geburtsdatum": "2014-01-08",
        "beziehung": "Partner",
        "altersklasse": "Kind"
      },
      {
        "vorname": "Mareike",
        "nachname": "Momsen",
        "geburtsdatum": "1960-11-06",
        "beziehung": "Kind",
        "altersklasse": "Erwachsener"
      }
    ],
    "monatsbeitrag": 54
  },
  "MCN-2021-000127": {
    "mitgliedsnummer": "MCN-2021-000127",
    "status": "Aktiv",
    "tarif": "Plus",
    "eintrittsdatum": "2021-05-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Svenja",
      "nachname": "Hinrichs",
      "geburtsdatum": "2005-08-28",
      "email": "svenja.hinrichs@example.de"
    },
    "adresse": {
      "strasse": "Billstedter Hauptstraße",
      "hausnummer": "65",
      "postleitzahl": "20357",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 0
  },
  "MCN-2021-000128": {
    "mitgliedsnummer": "MCN-2021-000128",
    "status": "Aktiv",
    "tarif": "Basis",
    "eintrittsdatum": "2021-06-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Lars",
      "nachname": "Momsen",
      "geburtsdatum": "1973-02-18",
      "email": "lars.momsen@example.de"
    },
    "adresse": {
      "strasse": "Osterstraße",
      "hausnummer": "3",
      "postleitzahl": "20357",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 12
  },
  "MCN-2024-000129": {
    "mitgliedsnummer": "MCN-2024-000129",
    "status": "Aktiv",
    "tarif": "Basis",
    "eintrittsdatum": "2024-10-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Thies",
      "nachname": "Wulff",
      "geburtsdatum": "1976-05-08",
      "email": "thies.wulff@example.de"
    },
    "adresse": {
      "strasse": "Osterstraße",
      "hausnummer": "28",
      "postleitzahl": "21073",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 12
  },
  "MCN-2019-000130": {
    "mitgliedsnummer": "MCN-2019-000130",
    "status": "Aktiv",
    "tarif": "Plus",
    "eintrittsdatum": "2019-09-01",
    "zahlungsart": "Rechnung",
    "hauptmitglied": {
      "vorname": "Sönke",
      "nachname": "Bahnsen",
      "geburtsdatum": "1968-11-09",
      "email": "sxnke.bahnsen@example.de"
    },
    "adresse": {
      "strasse": "Alsterchaussee",
      "hausnummer": "76",
      "postleitzahl": "22303",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 18
  },
  "MCN-2022-000131": {
    "mitgliedsnummer": "MCN-2022-000131",
    "status": "Aktiv",
    "tarif": "Basis",
    "eintrittsdatum": "2022-10-01",
    "zahlungsart": "Rechnung",
    "hauptmitglied": {
      "vorname": "Jannik",
      "nachname": "Jansen",
      "geburtsdatum": "2002-04-06",
      "email": "jannik.jansen@example.de"
    },
    "adresse": {
      "strasse": "Barmbeker Markt",
      "hausnummer": "3",
      "postleitzahl": "20357",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 8
  },
  "MCN-2022-000132": {
    "mitgliedsnummer": "MCN-2022-000132",
    "status": "Aktiv",
    "tarif": "Basis",
    "eintrittsdatum": "2022-11-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Sönke",
      "nachname": "Momsen",
      "geburtsdatum": "1979-09-02",
      "email": "sxnke.momsen@example.de"
    },
    "adresse": {
      "strasse": "Mühlenkamp",
      "hausnummer": "116",
      "postleitzahl": "20249",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 12
  },
  "MCN-2025-000133": {
    "mitgliedsnummer": "MCN-2025-000133",
    "status": "Aktiv",
    "tarif": "Basis",
    "eintrittsdatum": "2025-03-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Hauke",
      "nachname": "Hansen",
      "geburtsdatum": "1992-06-24",
      "email": "hauke.hansen@example.de"
    },
    "adresse": {
      "strasse": "Rübenkamp",
      "hausnummer": "54",
      "postleitzahl": "22765",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 12
  },
  "MCN-2025-000134": {
    "mitgliedsnummer": "MCN-2025-000134",
    "status": "Aktiv",
    "tarif": "Basis",
    "eintrittsdatum": "2025-11-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Birte",
      "nachname": "Paulsen",
      "geburtsdatum": "1982-08-04",
      "email": "birte.paulsen@example.de"
    },
    "adresse": {
      "strasse": "Große Bergstraße",
      "hausnummer": "86",
      "postleitzahl": "22089",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 12
  },
  "MCN-2021-000135": {
    "mitgliedsnummer": "MCN-2021-000135",
    "status": "Aktiv",
    "tarif": "Basis",
    "eintrittsdatum": "2021-11-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Wiebke",
      "nachname": "Hinrichs",
      "geburtsdatum": "1977-07-10",
      "email": "wiebke.hinrichs@example.de"
    },
    "adresse": {
      "strasse": "Osterstraße",
      "hausnummer": "118",
      "postleitzahl": "25524",
      "ort": "Itzehoe"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 12
  },
  "MCN-2023-000136": {
    "mitgliedsnummer": "MCN-2023-000136",
    "status": "Aktiv",
    "tarif": "Basis",
    "eintrittsdatum": "2023-05-01",
    "zahlungsart": "Rechnung",
    "hauptmitglied": {
      "vorname": "Broder",
      "nachname": "Hinrichs",
      "geburtsdatum": "1965-08-03",
      "email": "broder.hinrichs@example.de"
    },
    "adresse": {
      "strasse": "Holstenstraße",
      "hausnummer": "119",
      "postleitzahl": "21682",
      "ort": "Stade"
    },
    "familienmitglieder": [
      {
        "vorname": "Thies",
        "nachname": "Hinrichs",
        "geburtsdatum": "1979-10-20",
        "beziehung": "Kind",
        "altersklasse": "Erwachsener"
      },
      {
        "vorname": "Silke",
        "nachname": "Hinrichs",
        "geburtsdatum": "1996-01-02",
        "beziehung": "Kind",
        "altersklasse": "Junger Erwachsener"
      },
      {
        "vorname": "Jannik",
        "nachname": "Hinrichs",
        "geburtsdatum": "2000-06-28",
        "beziehung": "Kind",
        "altersklasse": "Junger Erwachsener"
      }
    ],
    "monatsbeitrag": 40
  },
  "MCN-2026-000137": {
    "mitgliedsnummer": "MCN-2026-000137",
    "status": "Aktiv",
    "tarif": "Basis",
    "eintrittsdatum": "2026-01-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Svenja",
      "nachname": "Timm",
      "geburtsdatum": "1962-10-05",
      "email": "svenja.timm@example.de"
    },
    "adresse": {
      "strasse": "Osterstraße",
      "hausnummer": "56",
      "postleitzahl": "21682",
      "ort": "Stade"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 12
  },
  "MCN-2020-000138": {
    "mitgliedsnummer": "MCN-2020-000138",
    "status": "Aktiv",
    "tarif": "Plus",
    "eintrittsdatum": "2020-09-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Wiebke",
      "nachname": "Bahnsen",
      "geburtsdatum": "1988-07-08",
      "email": "wiebke.bahnsen@example.de"
    },
    "adresse": {
      "strasse": "Holstenstraße",
      "hausnummer": "105",
      "postleitzahl": "23552",
      "ort": "Lübeck"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 18
  },
  "MCN-2020-000139": {
    "mitgliedsnummer": "MCN-2020-000139",
    "status": "Aktiv",
    "tarif": "Basis",
    "eintrittsdatum": "2020-01-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Hauke",
      "nachname": "Jansen",
      "geburtsdatum": "1969-03-19",
      "email": "hauke.jansen@example.de"
    },
    "adresse": {
      "strasse": "Billstedter Hauptstraße",
      "hausnummer": "6",
      "postleitzahl": "24103",
      "ort": "Kiel"
    },
    "familienmitglieder": [
      {
        "vorname": "Malte",
        "nachname": "Jansen",
        "geburtsdatum": "1991-12-15",
        "beziehung": "Partner",
        "altersklasse": "Erwachsener"
      },
      {
        "vorname": "Malte",
        "nachname": "Jansen",
        "geburtsdatum": "1963-05-08",
        "beziehung": "Kind",
        "altersklasse": "Erwachsener"
      }
    ],
    "monatsbeitrag": 36
  },
  "MCN-2022-000140": {
    "mitgliedsnummer": "MCN-2022-000140",
    "status": "Aktiv",
    "tarif": "Basis",
    "eintrittsdatum": "2022-06-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Imke",
      "nachname": "Ketelsen",
      "geburtsdatum": "1978-04-03",
      "email": "imke.ketelsen@example.de"
    },
    "adresse": {
      "strasse": "Fuhlsbüttler Straße",
      "hausnummer": "56",
      "postleitzahl": "21073",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 12
  },
  "MCN-2020-000141": {
    "mitgliedsnummer": "MCN-2020-000141",
    "status": "Aktiv",
    "tarif": "Plus",
    "eintrittsdatum": "2020-08-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Nils",
      "nachname": "Clausen",
      "geburtsdatum": "1992-04-10",
      "email": "nils.clausen@example.de"
    },
    "adresse": {
      "strasse": "Eppendorfer Landstraße",
      "hausnummer": "71",
      "postleitzahl": "23552",
      "ort": "Lübeck"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 18
  },
  "MCN-2019-000142": {
    "mitgliedsnummer": "MCN-2019-000142",
    "status": "Aktiv",
    "tarif": "Basis",
    "eintrittsdatum": "2019-09-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Jannik",
      "nachname": "Detlefsen",
      "geburtsdatum": "1987-10-07",
      "email": "jannik.detlefsen@example.de"
    },
    "adresse": {
      "strasse": "Lange Reihe",
      "hausnummer": "32",
      "postleitzahl": "21073",
      "ort": "Hamburg"
    },
    "familienmitglieder": [
      {
        "vorname": "Malte",
        "nachname": "Detlefsen",
        "geburtsdatum": "1997-04-05",
        "beziehung": "Kind",
        "altersklasse": "Junger Erwachsener"
      },
      {
        "vorname": "Nils",
        "nachname": "Detlefsen",
        "geburtsdatum": "1969-02-20",
        "beziehung": "Partner",
        "altersklasse": "Erwachsener"
      }
    ],
    "monatsbeitrag": 32
  },
  "MCN-2025-000143": {
    "mitgliedsnummer": "MCN-2025-000143",
    "status": "Aktiv",
    "tarif": "Plus",
    "eintrittsdatum": "2025-10-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Svenja",
      "nachname": "Boysen",
      "geburtsdatum": "1969-09-13",
      "email": "svenja.boysen@example.de"
    },
    "adresse": {
      "strasse": "Fuhlsbüttler Straße",
      "hausnummer": "95",
      "postleitzahl": "22303",
      "ort": "Hamburg"
    },
    "familienmitglieder": [
      {
        "vorname": "Silke",
        "nachname": "Boysen",
        "geburtsdatum": "2011-01-02",
        "beziehung": "Kind",
        "altersklasse": "Kind"
      },
      {
        "vorname": "Antje",
        "nachname": "Boysen",
        "geburtsdatum": "1980-11-27",
        "beziehung": "Kind",
        "altersklasse": "Erwachsener"
      }
    ],
    "monatsbeitrag": 36
  },
  "MCN-2021-000144": {
    "mitgliedsnummer": "MCN-2021-000144",
    "status": "Aktiv",
    "tarif": "Plus",
    "eintrittsdatum": "2021-03-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Hauke",
      "nachname": "Harms",
      "geburtsdatum": "1989-09-01",
      "email": "hauke.harms@example.de"
    },
    "adresse": {
      "strasse": "Osterstraße",
      "hausnummer": "3",
      "postleitzahl": "22765",
      "ort": "Hamburg"
    },
    "familienmitglieder": [
      {
        "vorname": "Ole",
        "nachname": "Harms",
        "geburtsdatum": "1972-07-03",
        "beziehung": "Kind",
        "altersklasse": "Erwachsener"
      },
      {
        "vorname": "Imke",
        "nachname": "Harms",
        "geburtsdatum": "1964-10-15",
        "beziehung": "Partner",
        "altersklasse": "Erwachsener"
      }
    ],
    "monatsbeitrag": 54
  },
  "MCN-2023-000145": {
    "mitgliedsnummer": "MCN-2023-000145",
    "status": "Aktiv",
    "tarif": "Basis",
    "eintrittsdatum": "2023-07-01",
    "zahlungsart": "Rechnung",
    "hauptmitglied": {
      "vorname": "Frauke",
      "nachname": "Clausen",
      "geburtsdatum": "1969-11-24",
      "email": "frauke.clausen@example.de"
    },
    "adresse": {
      "strasse": "Holstenstraße",
      "hausnummer": "83",
      "postleitzahl": "20357",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 12
  },
  "MCN-2025-000146": {
    "mitgliedsnummer": "MCN-2025-000146",
    "status": "Aktiv",
    "tarif": "Basis",
    "eintrittsdatum": "2025-10-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Hauke",
      "nachname": "Nissen",
      "geburtsdatum": "1986-06-13",
      "email": "hauke.nissen@example.de"
    },
    "adresse": {
      "strasse": "Billstedter Hauptstraße",
      "hausnummer": "119",
      "postleitzahl": "20249",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 12
  },
  "MCN-2026-000147": {
    "mitgliedsnummer": "MCN-2026-000147",
    "status": "Ruhend",
    "tarif": "Basis",
    "eintrittsdatum": "2026-08-01",
    "zahlungsart": "Rechnung",
    "hauptmitglied": {
      "vorname": "Mareike",
      "nachname": "Bahnsen",
      "geburtsdatum": "1959-09-05",
      "email": "mareike.bahnsen@example.de"
    },
    "adresse": {
      "strasse": "Billstedter Hauptstraße",
      "hausnummer": "5",
      "postleitzahl": "20249",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 12
  },
  "MCN-2025-000148": {
    "mitgliedsnummer": "MCN-2025-000148",
    "status": "Beendet",
    "tarif": "Basis",
    "eintrittsdatum": "2025-04-01",
    "zahlungsart": "Rechnung",
    "hauptmitglied": {
      "vorname": "Anna",
      "nachname": "Hinrichs",
      "geburtsdatum": "1965-04-25",
      "email": "anna.hinrichs@example.de"
    },
    "adresse": {
      "strasse": "Lange Reihe",
      "hausnummer": "94",
      "postleitzahl": "24103",
      "ort": "Kiel"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 12
  },
  "MCN-2024-000149": {
    "mitgliedsnummer": "MCN-2024-000149",
    "status": "Ruhend",
    "tarif": "Plus",
    "eintrittsdatum": "2024-04-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Wiebke",
      "nachname": "Rohwedder",
      "geburtsdatum": "1976-05-25",
      "email": "wiebke.rohwedder@example.de"
    },
    "adresse": {
      "strasse": "Barmbeker Markt",
      "hausnummer": "4",
      "postleitzahl": "22303",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 18
  },
  "MCN-2023-000150": {
    "mitgliedsnummer": "MCN-2023-000150",
    "status": "Aktiv",
    "tarif": "Basis",
    "eintrittsdatum": "2023-12-01",
    "zahlungsart": "Rechnung",
    "hauptmitglied": {
      "vorname": "Wiebke",
      "nachname": "Jansen",
      "geburtsdatum": "1996-01-24",
      "email": "wiebke.jansen@example.de"
    },
    "adresse": {
      "strasse": "Osterstraße",
      "hausnummer": "37",
      "postleitzahl": "23552",
      "ort": "Lübeck"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 8
  },
  "MCN-2022-000151": {
    "mitgliedsnummer": "MCN-2022-000151",
    "status": "Aktiv",
    "tarif": "Plus",
    "eintrittsdatum": "2022-04-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Frauke",
      "nachname": "Wulff",
      "geburtsdatum": "1991-05-13",
      "email": "frauke.wulff@example.de"
    },
    "adresse": {
      "strasse": "Eppendorfer Landstraße",
      "hausnummer": "16",
      "postleitzahl": "20357",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 18
  },
  "MCN-2020-000152": {
    "mitgliedsnummer": "MCN-2020-000152",
    "status": "Aktiv",
    "tarif": "Plus",
    "eintrittsdatum": "2020-10-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Antje",
      "nachname": "Momsen",
      "geburtsdatum": "2001-12-02",
      "email": "antje.momsen@example.de"
    },
    "adresse": {
      "strasse": "Barmbeker Markt",
      "hausnummer": "3",
      "postleitzahl": "23552",
      "ort": "Lübeck"
    },
    "familienmitglieder": [
      {
        "vorname": "Nils",
        "nachname": "Momsen",
        "geburtsdatum": "1982-06-11",
        "beziehung": "Partnerin",
        "altersklasse": "Erwachsener"
      }
    ],
    "monatsbeitrag": 30
  },
  "MCN-2019-000153": {
    "mitgliedsnummer": "MCN-2019-000153",
    "status": "Aktiv",
    "tarif": "Plus",
    "eintrittsdatum": "2019-10-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Broder",
      "nachname": "Struve",
      "geburtsdatum": "1957-02-17",
      "email": "broder.struve@example.de"
    },
    "adresse": {
      "strasse": "Große Bergstraße",
      "hausnummer": "1",
      "postleitzahl": "21682",
      "ort": "Stade"
    },
    "familienmitglieder": [
      {
        "vorname": "Frauke",
        "nachname": "Struve",
        "geburtsdatum": "1966-07-10",
        "beziehung": "Partner",
        "altersklasse": "Erwachsener"
      },
      {
        "vorname": "Wiebke",
        "nachname": "Struve",
        "geburtsdatum": "2017-01-28",
        "beziehung": "Partnerin",
        "altersklasse": "Kind"
      }
    ],
    "monatsbeitrag": 36
  },
  "MCN-2021-000154": {
    "mitgliedsnummer": "MCN-2021-000154",
    "status": "Aktiv",
    "tarif": "Plus",
    "eintrittsdatum": "2021-05-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Broder",
      "nachname": "Bahnsen",
      "geburtsdatum": "1955-11-17",
      "email": "broder.bahnsen@example.de"
    },
    "adresse": {
      "strasse": "Holstenstraße",
      "hausnummer": "106",
      "postleitzahl": "25524",
      "ort": "Itzehoe"
    },
    "familienmitglieder": [
      {
        "vorname": "Broder",
        "nachname": "Bahnsen",
        "geburtsdatum": "2001-05-15",
        "beziehung": "Kind",
        "altersklasse": "Junger Erwachsener"
      }
    ],
    "monatsbeitrag": 30
  },
  "MCN-2026-000155": {
    "mitgliedsnummer": "MCN-2026-000155",
    "status": "Aktiv",
    "tarif": "Basis",
    "eintrittsdatum": "2026-04-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Wiebke",
      "nachname": "Rohwedder",
      "geburtsdatum": "1993-06-17",
      "email": "wiebke.rohwedder@example.de"
    },
    "adresse": {
      "strasse": "Große Bergstraße",
      "hausnummer": "45",
      "postleitzahl": "23552",
      "ort": "Lübeck"
    },
    "familienmitglieder": [
      {
        "vorname": "Imke",
        "nachname": "Rohwedder",
        "geburtsdatum": "2000-07-19",
        "beziehung": "Partnerin",
        "altersklasse": "Junger Erwachsener"
      }
    ],
    "monatsbeitrag": 20
  },
  "MCN-2023-000156": {
    "mitgliedsnummer": "MCN-2023-000156",
    "status": "Beendet",
    "tarif": "Plus",
    "eintrittsdatum": "2023-09-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Ole",
      "nachname": "Thomsen",
      "geburtsdatum": "1986-12-20",
      "email": "ole.thomsen@example.de"
    },
    "adresse": {
      "strasse": "Rübenkamp",
      "hausnummer": "120",
      "postleitzahl": "23552",
      "ort": "Lübeck"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 18
  },
  "MCN-2022-000157": {
    "mitgliedsnummer": "MCN-2022-000157",
    "status": "Ruhend",
    "tarif": "Plus",
    "eintrittsdatum": "2022-06-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Imke",
      "nachname": "Ketelsen",
      "geburtsdatum": "1964-01-02",
      "email": "imke.ketelsen@example.de"
    },
    "adresse": {
      "strasse": "Mühlenkamp",
      "hausnummer": "3",
      "postleitzahl": "21682",
      "ort": "Stade"
    },
    "familienmitglieder": [
      {
        "vorname": "Heike",
        "nachname": "Ketelsen",
        "geburtsdatum": "1994-09-26",
        "beziehung": "Partnerin",
        "altersklasse": "Junger Erwachsener"
      },
      {
        "vorname": "Thies",
        "nachname": "Ketelsen",
        "geburtsdatum": "1986-06-24",
        "beziehung": "Kind",
        "altersklasse": "Erwachsener"
      }
    ],
    "monatsbeitrag": 48
  },
  "MCN-2020-000158": {
    "mitgliedsnummer": "MCN-2020-000158",
    "status": "Aktiv",
    "tarif": "Basis",
    "eintrittsdatum": "2020-02-01",
    "zahlungsart": "Rechnung",
    "hauptmitglied": {
      "vorname": "Nils",
      "nachname": "Boysen",
      "geburtsdatum": "1967-05-18",
      "email": "nils.boysen@example.de"
    },
    "adresse": {
      "strasse": "Mühlenkamp",
      "hausnummer": "20",
      "postleitzahl": "22303",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 12
  },
  "MCN-2019-000159": {
    "mitgliedsnummer": "MCN-2019-000159",
    "status": "Aktiv",
    "tarif": "Plus",
    "eintrittsdatum": "2019-02-01",
    "zahlungsart": "SEPA",
    "hauptmitglied": {
      "vorname": "Sönke",
      "nachname": "Bahnsen",
      "geburtsdatum": "1981-12-27",
      "email": "sxnke.bahnsen@example.de"
    },
    "adresse": {
      "strasse": "Fuhlsbüttler Straße",
      "hausnummer": "50",
      "postleitzahl": "20249",
      "ort": "Hamburg"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 18
  },
  "MCN-2021-000160": {
    "mitgliedsnummer": "MCN-2021-000160",
    "status": "Aktiv",
    "tarif": "Plus",
    "eintrittsdatum": "2021-03-01",
    "zahlungsart": "Rechnung",
    "hauptmitglied": {
      "vorname": "Thies",
      "nachname": "Rohwedder",
      "geburtsdatum": "2006-09-09",
      "email": "thies.rohwedder@example.de"
    },
    "adresse": {
      "strasse": "Fuhlsbüttler Straße",
      "hausnummer": "88",
      "postleitzahl": "25524",
      "ort": "Itzehoe"
    },
    "familienmitglieder": [],
    "monatsbeitrag": 0
  }
};

module.exports = { mitglieder };
