// Generates data.js with 100 deterministic mock applicants.
// Deterministic (seeded) so re-running this script produces identical output —
// safe to regenerate without breaking anything students have already tested.
// Run: node scripts/generate-data.js

const fs = require("fs");
const path = require("path");

// Simple seeded PRNG (mulberry32) for reproducible output.
function mulberry32(seed) {
  return function () {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rand = mulberry32(20260917); // seed = today's date, arbitrary but fixed

const firstNames = [
  "Maria", "Jonas", "Elena", "Tom", "Sophie", "Lukas", "Anna", "Felix",
  "Laura", "Paul", "Nina", "David", "Julia", "Simon", "Clara", "Max",
  "Lena", "Peter", "Sarah", "Michael", "Eva", "Daniel", "Hannah", "Stefan",
];

const lastNames = [
  "Novak", "Berger", "Kovacs", "Fischer", "Wagner", "Huber", "Gruber",
  "Steiner", "Maier", "Weber", "Winkler", "Bauer", "Lang", "Schmid",
  "Koller", "Brunner", "Leitner", "Pichler", "Wolf", "Eder",
];

const streets = [
  "Ringstrasse", "Mariahilfer Str", "Praterstrasse", "Landstrasser Hauptstr",
  "Favoritenstrasse", "Neubaugasse", "Gumpendorfer Str", "Westbahnstrasse",
  "Hauptstrasse", "Schoenbrunner Str", "Taborstrasse", "Alserbachstrasse",
];

const postalCodes = ["1010", "1020", "1030", "1060", "1070", "1090", "1100", "1120", "1150", "1200"];

const employmentStatuses = ["Employed", "Employed", "Employed", "Self-Employed", "Unemployed"];

function pick(arr) {
  return arr[Math.floor(rand() * arr.length)];
}

function randInt(min, max) {
  return Math.floor(rand() * (max - min + 1)) + min;
}

function pad(n, width) {
  return String(n).padStart(width, "0");
}

const APPLICANT_COUNT = 100;
const applicants = {};

// Reserve a handful of deliberate name collisions up front (indices 0-9) so a
// name-only search reliably returns multiple matches for training. The rest
// are randomized and may occasionally collide too (realistic noise).
const collisionPairs = [
  ["Jonas", "Berger"],
  ["Anna", "Huber"],
  ["Maria", "Novak"],
  ["Tom", "Fischer"],
  ["Lena", "Wolf"],
];

const forcedNames = [];
collisionPairs.forEach(([fn, ln]) => {
  forcedNames.push([fn, ln]);
  forcedNames.push([fn, ln]);
});

for (let i = 1; i <= APPLICANT_COUNT; i++) {
  const applicantId = `APP${pad(1000 + i, 4)}`;
  const [firstName, lastName] =
    i <= forcedNames.length ? forcedNames[i - 1] : [pick(firstNames), pick(lastNames)];

  const year = randInt(1965, 2004);
  const month = pad(randInt(1, 12), 2);
  const day = pad(randInt(1, 28), 2);
  const dateOfBirth = `${year}-${month}-${day}`;

  const employmentStatus = pick(employmentStatuses);
  const annualIncome = employmentStatus === "Unemployed" ? 0 : randInt(28, 140) * 1000;

  // Credit score correlated loosely with income + a random factor, clamped 300-850.
  const base = employmentStatus === "Unemployed" ? 480 : 560 + Math.floor(annualIncome / 2000);
  const noise = randInt(-80, 90);
  const creditScore = Math.max(300, Math.min(850, base + noise));

  let riskBand;
  if (creditScore >= 750) riskBand = "Excellent";
  else if (creditScore >= 700) riskBand = "Good";
  else if (creditScore >= 650) riskBand = "Fair";
  else if (creditScore >= 580) riskBand = "Poor";
  else riskBand = "Very Poor";

  applicants[applicantId] = {
    applicantId,
    ssn: `111-22-${pad(1000 + i, 4)}`,
    firstName,
    lastName,
    dateOfBirth,
    address: {
      street: `${randInt(1, 99)} ${pick(streets)}`,
      city: "Vienna",
      postalCode: pick(postalCodes),
      country: "AT",
    },
    employmentStatus,
    annualIncome,
    creditScore,
    riskBand,
  };
}

const banner = `// AUTO-GENERATED by scripts/generate-data.js — do not hand-edit.
// Regenerate with: node scripts/generate-data.js
//
// ${APPLICANT_COUNT} deterministic mock applicants for the Pega training exercise.
// The first ${forcedNames.length} entries (APP1001-APP${pad(1000 + forcedNames.length, 4)}) are
// deliberate name collisions in ${collisionPairs.length} pairs, so a name-only search on
// Applicant Search reliably returns multiple matches for the disambiguation exercise:
${collisionPairs.map((p) => `//   - ${p[0]} ${p[1]}`).join("\n")}
// All other entries are randomized (fixed seed, so this file is reproducible).
`;

const output =
  banner +
  "\nconst applicants = " +
  JSON.stringify(applicants, null, 2) +
  ";\n\nmodule.exports = { applicants };\n";

fs.writeFileSync(path.join(__dirname, "..", "data.js"), output);
console.log(`Wrote ${APPLICANT_COUNT} applicants to data.js`);
